### ISSUE TITLE
Socket Error: An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by SpadesNeil** [LCN-Dev/GoogleBot#96]
#### Brief description of the issue:
The connection is being aborted by software in the host machine. Research indicates this might be due to firewalls or virus protection.

`***STOPPING GOOGLE SPEECH RECO***
Socket error: System.Net.Sockets.SocketException (0x80004005): An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.Socket.Receive(Byte[] buffer)
   at AutoBotCSharp.Speech_Recognizer.<reco_google>d__43.MoveNext() in C:\Users\3g5mbm1\Documents\GitHub\GoogleBot\AutoBotCSharp\Speech_Recognizer.cs:line 143`

#### What happened?:
Bot crashes when this error occurs.

#### What _should_ have happened?:
Bot should not crash, and speech reco should reset.

#### Steps to reproduce:
Unknown

#### Additional info:
 - **Bot Revision**: https://github.com/LCN-Dev/GoogleBot/commit/607db7295f305aa8e184c9149cc33e650418bf86

**Comment by SpadesNeil** [comment]
I noticed one instance where "was called successfully" spammed the console prior to crash.

**Comment by SpadesNeil** [comment]
This wasn't related to the issue we had.
